# Generated by Django 6.0.3 on 2026-03-16 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('app_password', models.CharField(max_length=255)),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=120)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GmailTicketThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(db_index=True, max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_thread', to='core.ticket')),
            ],
        ),
    ]
